spring:
  #profile
  profiles:
    active: dev
  #springdevtools
  devtools:
    restart:
      enabled: true

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spurious.bilibili.dao

